version: "3.8"

services:
  redis:
    image: redis
    container_name: sponsorcord_redis

  mysql:
    image: mysql
    container_name: sponsorcord_mysql
    environment:
      MYSQL_DATABASE: "sponsorcord"
      MYSQL_USER: "sponsorcord"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "${TZ}"
    volumes:
      - sponsorcord-mysql:/var/lib/mysql

  app:
    image: prytz/sponsorcord
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      REDIS_HOST: "redis"
      PORT: "${PORT}"
      TZ: "${TZ}"

      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      DISCORD_REDIRECT_URI: "${DISCORD_REDIRECT_URI}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      GITHUB_REDIRECT_URI: "${GITHUB_REDIRECT_URI}"
      GITHUB_WEBHOOK_SECRET: "${GITHUB_WEBHOOK_SECRET}"
    depends_on:
      - mysql
      - redis
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    container_name: sponsorcord_app

volumes:
  sponsorcord-mysql:
